"""add shoppingcart

Revision ID: 303d01e149d9
Revises: 70e59bcb3c57
Create Date: 2023-06-13 08:23:27.978828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303d01e149d9'
down_revision = '70e59bcb3c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingcarts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_shoppingcarts_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shoppingcarts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcarts')
    # ### end Alembic commands ###
