"""change enrollment status

Revision ID: 99d564b5b195
Revises: 303d01e149d9
Create Date: 2023-06-13 13:42:02.189313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d564b5b195'
down_revision = '303d01e149d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('registered', 'cancelled', 'waitlist', name='enrollment_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('registered', 'cancelled', 'waitlist', name='enrollment_status'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
