"""add role

Revision ID: c6c25079c8e9
Revises: 77ace60a8233
Create Date: 2023-06-15 09:39:10.885648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c25079c8e9'
down_revision = '77ace60a8233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='student', nullable=False))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='teacher', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
