"""simplify enrollment status

Revision ID: c85b6dba8f44
Revises: c6c25079c8e9
Create Date: 2023-06-19 10:05:40.299751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85b6dba8f44'
down_revision = 'c6c25079c8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
