lesson_titles = [
    "History and Origins of the Japanese Tea Ceremony",
    "Understanding the Tea Ceremony Equipment",
    "Basic Etiquette and Bowing Techniques",
    "Preparing the Tea Room",
    "Seating Arrangements and Guest Hosting",
    "Proper Way to Wear a Kimono for Tea Ceremony",
    "Introduction to Matcha Tea",
    "Different Grades of Matcha Tea and Their Significance",
    "Preparing the Tea Utensils",
    "Whisking Techniques for Matcha Tea",
    "Measuring and Mixing Matcha Tea",
    "Pouring Techniques and the Art of Serving",
    "Mastering the Tea Scoop (Chashaku)",
    "Appreciating the Tea Bowl (Chawan)",
    "Understanding the Tea Caddy (Natsume)",
    "Importance of the Tea Whisk (Chasen)",
    "Decorative Elements in the Tea Room",
    "Creating the Perfect Atmosphere with Incense",
    "Zen Principles and Mindfulness in Tea Ceremony",
    "Cleansing Rituals and Purification",
    "Appreciating the Seasonal Elements in Tea Ceremony",
    "Poetry and Calligraphy in Tea Ceremony",
    "Tea Ceremony and Traditional Japanese Aesthetics",
    "Tea Ceremony in Contemporary Japanese Culture",
    "Hosting a Tea Gathering (Chakai)",
    "Tea Ceremony for Special Occasions",
    "Tea Ceremony and the Way of Tea (Chado)",
    "Etiquette for Tea Ceremony Guests",
    "Tea Ceremony and Cultural Significance",
    "Tea Ceremony and Tea Gardens",
    "Practice Session: Conducting a Miniature Tea Ceremony"
]
